server:
  servlet:
    context-path: /report
  port: 8300
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8100/uaa/oauth/check_token
      user-info-uri: http://localhost:8100/uaa/user/current
    client:
      client-id: CLIENT_REPORT_ID
      client-secret: password
